### ISSUE TITLE
[feature] Ability to filter non-resolving domains

### ISSUE THREAD

**Issue by BastienFaure** [projectdiscovery/dnsx#11]
Hello,

I really like this tool, especially since it is crazy fast and it does exactly what I want :D That being said, I usually have the need to remove hostnames from a list, for instance those who do not resolve to any IPv4 address. I know that I can do `dnsx -a -cname` to print only domains with a A or CNAME record but I wish I could have only domain who:
* have an A record
* have at least one CNAME that itself has an A record

It might be a little out of the scope of the tool's purpose but if such a thing is either planned or in current development, I'd like to hear more about it :)

**Comment by team-projectdiscovery** [comment]
Hi @BastienFaure, 

Thank you, not sure what's the use case it misses when you do something like this `cat subs.txt | dnsx`, this will ensure to print only subs having A record, otherwise, do you have any example to share?

**Comment by BastienFaure** [comment]
Hey @team-projectdiscovery thanks for your quick response ! Sorry if I was unclear. Let's take the hostname `azertyuiop.faure.io`.
I does have a valid CNAME record and no A record. The CNAME records has no A record and thus I was chasing the ability to filter all the domains that do not have, at the end of the CNAME chain, none of an A or AAAA record. Does that make sense ?

Like:
* `coolcname.test.com` -> `google.com` -> a A record: OK
* `notcoolcname.test.com` -> `idonotexistatall.com` -> no A record: NOK

It would require some kind of recursion in case there are nested CNAMEs, if you got my point.

**Comment by team-projectdiscovery** [comment]
Hi @BastienFaure, 

I still don't get the full context but based on what I understood I'm going to list the possible solutions:- 

```
azertyuiop.faure.io
docs.hackerone.com
```

`azertyuiop.faure.io > CNAME > NO A`
`docs.hackerone.com > CNAME > A`

And if you do `cat test.txt | dnsx` only `docs.hackerone.com` will get printed as it has A record at the end, is that what you looking for? 

If not, we have another tool called [nuclei](https://github.com/projectdiscovery/nuclei) using same library as `dnsx` that let you write workflows for custom conditions, you can have look at some existing [DNS based templates](https://github.com/projectdiscovery/nuclei-templates/tree/master/dns) to write your own template.

**Comment by BastienFaure** [comment]
@team-projectdiscovery exactly ! I'm happy to try out it nuclei if it provides this ability, thanks !

**Comment by team-projectdiscovery** [comment]
Sure @BastienFaure, if this answers your question, we can close this out.

**Comment by team-projectdiscovery** [comment]
Closing as no action needed here.
