### ISSUE TITLE
stdin support for domain / wordlist flag

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/dnsx#137]
### Please describe your feature request:

Currently, `list` input supports `stdin` as default, with addition [wordlist based DNS brute-forcing](https://github.com/projectdiscovery/dnsx/pull/130), we can extend this support for other input flags as well, including `domain` and `wordlist`.

Flag for `stdin` can be indicated with a specific marker(`-`) with validation to ensure only one flag is getting used for `stdin`

```yaml
$ cat subs.txt | dnsx  # as default, stdin is used for list flag
$ cat words.txt | dnsx -d google.com,youtube.com -w - # wordlist flag with stdin support
$ echo jira,confluence | dnsx -d domains.txt -w - # wordlist flag with stdin support
$ echo google.com,youtube.com | dnsx -w words.txt -d - # domain flag with stdin support

$ echo google.com,youtube.com | dnsx -w - -d - # validation for multiple stdin
multiple flags with stdin can not be specified
```

### Describe the use case of this feature:
to ease automation around dnsx

**Comment by brenocss** [comment]
Would be great if you could choose the wordlist placeholder like ffuf
 ```zsh
 cat list.txt | ffuf -u http://127.0.0.1/FUZZ -w - 
 ```
 ```zsh
 cat tldlist.txt | dnsx  -d "google.FUZZ" -w - 
 ```
  ```zsh
 cat tldlist.txt | dnsx  -d "DOMAINS.FUZZ" -w -:FUZZ  -w domains.txt:DOMAINS
 ```

**Comment by ehsandeep** [comment]
thanks for sharing this idea @brenocss, we will keep this in mind for future updates.
