### ISSUE TITLE
allow/deny host list support

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/dnsx#140]
### Please describe your feature request:
Porting **allow/deny** support from [httpx](https://github.com/projectdiscovery/httpx/issues/374) to dnsx 

### Describe the use case of this feature:
allows us to define which hosts to be passed through or denied for processing.

**Comment by brenocss** [comment]
unlike httpx, i believe dnsx should use deny and match list to create a field in json
```zsh
echo 'localhost.tld'  |  dnsx -deny 127.0.0.1 -json -match 192.168.0.1
```
```json
{
  "host": "localhost.tld",
  "resolver": [
    "1.0.0.1:53"
  ],
  "a": [
    "127.0.0.1"
  ],
  "status_code": "NOERROR",
  "timestamp": "2022-01-15T18:23:30.841005537Z"
 "deny": true
 "match": false
}
```
- Use cases
```bash
cat domainnames  |  dnsx -match cloudipranges -deny cdniprange -json | anew log.json
# Get all hostnames that belong to cloud
cat log.json |  jq 'select(.match==true).host'
# Get all hostnames that don't belong to cdn
cat log.json |  jq 'select(.deny==true).host'
```

**Comment by ehsandeep** [comment]
Closing this ticket, as allow/deny can be only supported after perfroming dns resolution.
