### ISSUE TITLE
homebrew support

### ISSUE THREAD

**Issue by chenrui333** [projectdiscovery/dnsx#15]
👋  FYI, Since [dnsprobe is deprecated](https://github.com/projectdiscovery/dnsprobe/commit/71b5f9ab6f2ef0ec88543f06b5a88e4b0882d433) in favor of this utility, I have [filed a PR](https://github.com/Homebrew/homebrew-core/pull/67797) to include this into homebrew-core. Thanks!

**Comment by bauthard** [comment]
@chenrui333 looks like PR is already merged, as such, can we close this out?

**Comment by chenrui333** [comment]
yeah, totally!
