### ISSUE TITLE
Bug with temporary files at /tmp

### ISSUE THREAD

**Issue by sumgr0** [projectdiscovery/dnsx#158]
Hi Team!

I've been using dnsx for continuous monitoring for few months now on a large dataset. However, recently my VPS started having low disk space and while investigating the reasons for the same I believe its due to the recent update to dnsx tool.

I've noticed that dnsx generates a folder in /tmp starting with hm*, while version 1.0.7 handled it appropriately, the latest version seems to be creating hm* and not deleting it after the completion of the process.

I've tried downgrading to the 1.0.7 and faced no issues with space during the same processes running as with 1.0.8.

So, I request you to kindly have a look to fix the same.

Thanks

**Comment by sumgr0** [comment]
This was discovered after successful elaboration (completion of the task). The behavior was not tested with CTRL+C since as mentioned, the workflow requires continuous monitoring.

I'm certain it occurs with version 1.0.8, as last week the tool got updated accidentally and resulted in crashing of multiple services due to non clean-up of the /tmp/hm* folders, which took about 40% of the disk space.

Hope this helps.

**Comment by ehsandeep** [comment]
@sumgr0 should be fixed with the latest version of the project, thanks again for reporting this.
