### ISSUE TITLE
-output file gives partial results with a large domains list

### ISSUE THREAD

**Issue by swdbo** [projectdiscovery/dnsx#190]
Hello !

### dnsx version:
v1.1.0
Tested on MacOS & Debian 

### Current Behavior:
For a large list of domains, dnsx only prints the first ~180 000 resolved domains in the output file passed with the -o options

### Expected Behavior:
Output should reflect all the resolved domains

### Steps To Reproduce:

`$ cat domains.txt |  dnsx -silent -o output.txt`
`cat output.txt`
domains.txt should contain at least 200 000 or 300 000 resolving domains.

### Anything else:
With a 2 millions domains file gathered with subfinder, the output file will stop at the letter A or B.

**Comment by ehsandeep** [comment]
@swdbo thanks for sharing this; few question:

a) is it something you are able to reproduce all the time?
b) do you see additional results being printed to CLI and not written to file?
c) is the scan still continuing and only results not being written?

**Comment by swdbo** [comment]
@ehsandeep 

a) yes : all the time. Same behaviour on MacOS and Debian.

b) I do see additional results printed (so the resolving part seems to work), but the output file does not reflect it

c) the scan is continuing until the end, no warning / error.
But your question made me want to a simple `cat domains.txt | dnsx -silent -o output.txt | tee output_tee.txt`
(wc -l domains.txt      => 300 000 lines)
 wc -l output.txt          =>   32 685 lines
 wc -l output_tee.txt  =>  182 890 lines
