### ISSUE TITLE
Return cdn check and provider in dnsx 

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/dnsx#204]
### Please describe your feature request:

https://github.com/projectdiscovery/httpx/issues/492
### Describe the use case of this feature:

dnsx can be the CLI for [cdn-check](https://github.com/projectdiscovery/cdncheck).
```zsh
echo 'www.hackerone.com' | dnsx -cdn
www.hackerone.com [cloudflare]
```

**Comment by KickAss101** [comment]
Can you confirm if cdn flag is working? It's not working for me. Tried tool with `go install` and from releases. Didn't work in both instances.

![Screenshot_20221008_225203](https://user-images.githubusercontent.com/46389158/194719856-7ee2920c-0555-4c90-92c1-1bd4af604e77.png)
