### ISSUE TITLE
add option to tell us which ones resolve to internal ips

### ISSUE THREAD

**Issue by 0xAwali** [projectdiscovery/dnsx#209]
it's possible to add option to tell us which ones resolve to internal ips e.g. similar to  [hakfindinternaldomains](https://github.com/hakluke/hakfindinternaldomains)

```
cat subs.txt | dnsx -a -internal
sub.comapny.com [192.88.99.44] [Internal]
```

**Comment by brenocss** [comment]
https://github.com/projectdiscovery/dnsx/issues/139

**Comment by 0xAwali** [comment]
thanks @brenocss I didn't know that

**Comment by Mzack9999** [comment]
@0xAwali, this is already possible with `jq` filtering. I'm converting the issue into a discussion. Please let us know if you think we can make any further improvements. Thanks!
