### ISSUE TITLE
Bug in "axfr" detection

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/dnsx#230]
### dnsx version:
dev

### Current Behavior:
`axfr` being detected for unrelated hosts.

### Expected Behavior:
correctly detecting axfr

### Steps To Reproduce:

```console
echo skypixel.com | ./dnsx -axfr

skypixel.com
```

### Anything else:
valid host with enabled `axfr` - `zonetransfer.me`

continuation of https://github.com/projectdiscovery/dnsx/pull/173

**Comment by Mzack9999** [comment]
I don't think that `afxr` is detected. There is no  `"is_zone_transfer": true` and `axfr` data is empty:
```console
$ echo skypixel.com | go run . -axfr -json
...
{"host":"skypixel.com","resolver":["1.0.0.1:53"],"a":["47.254.56.245"],"all":["skypixel.com.\t171\tIN\tA\t47.254.56.245","\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags: ; udp: 1232"],"status_code":"NOERROR","axfr":{"host":"skypixel.com"},"timestamp":"2022-09-19T08:05:30.6207826+02:00"}
```
Initially, filtering zone transfers enabled servers were meant as a secondary step to perform with jq. Do you want to implement changes in the current output logic (not outputting hosts if they haven't specific query-related data)?

**Comment by ehsandeep** [comment]
> not outputting hosts if they haven't specific query-related data

@Mzack9999 I see, and yes, we want to return host/result only in case of `axfr` is enabled on a given host.
