### ISSUE TITLE
Piped domain does not work with wordlist brute-forcing

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/dnsx#234]
![image](https://user-images.githubusercontent.com/13679401/188634938-f5673183-8a8c-4f2c-b742-bcc948467005.png)

**Comment by ehsandeep** [comment]
@forgedhallpass the working example for above is `echo projectdiscovery.io | dnsx -w nuclei,www -d -`

> dnsx support stdin input for all the input flags (list,domain,wordlist), as default l flag is supported for stdin, other input flag can be used by specifying the flag input with dash (-).

as default `stdin` input used for `-l` option and not as domain (`-d`) which is required input for wordlist bruteforce.

**Comment by ehsandeep** [comment]
Closing as not planned.

**Comment by forgedhallpass** [comment]
> @forgedhallpass the working example for above is `echo projectdiscovery.io | dnsx -w nuclei,www -d -`
> 
> > dnsx support stdin input for all the input flags (list,domain,wordlist), as default l flag is supported for stdin, other input flag can be used by specifying the flag input with dash (-).
> 
> as default `stdin` input used for `-l` option and not as domain (`-d`) which is required input for wordlist bruteforce.

IMO it is very counter-intuitive and redundant to require `-d -` when you've already passed in a wordlist (which only makes sense for brute-forcing) and a target. Furthermore the `-d` and `-l` flags should be merged, because it suggests that you can start two actions at once and the results will be merged, which is not true at the moment (see below), nor is uniform with the other PD tools. Just my 2c.

See:
```shell
echo example.com | dnsx -d projectdiscovery.io -w www,blog -silent
    blog.projectdiscovery.io
    www.projectdiscovery.io

dnsx -l input.txt -d projectdiscovery.io -w www -silent
    [FTL] list(l) flag can not be used domain(d) or wordlist(w) flag
```
