### ISSUE TITLE
[feature] Combine results when multiple records

### ISSUE THREAD

**Issue by Techbrunch** [projectdiscovery/dnsx#24]
Not sure if that would cause other issues but I think an option to combine results for a record type would be nice.

**Before**

```
echo hackerone.com | dnsx -a -silent -resp
hackerone.com [104.16.100.52]
hackerone.com [104.16.99.52]
```

**After**

```
echo hackerone.com | dnsx -a -silent -resp
hackerone.com [104.16.100.52, 104.16.99.52]
```

**Comment by ehsandeep** [comment]
@Techbrunch, unfortunately, we can not make this change to maintain the uniform output with `-resp` and `resp-only` flag, additionally, you can make use of `-json` flag to extract the data you want.
