### ISSUE TITLE
Upgrade zstd dependency

### ISSUE THREAD

**Issue by thesamesam** [projectdiscovery/dnsx#240]
dnsx 1.1.1 depends on zstd-1.4.5. Unfortunately, this version is quite old and doesn't support using the system copy of the zstd library like newer versions do (I'm using 1.5.2 locally which works) as described at https://github.com/DataDog/zstd#building-against-an-external-libzstd.

Is there any chance the zstd dependency could be upgraded, or do I need to file a bug with one of dnsx's dependencies instead? Thanks!

**Comment by ehsandeep** [comment]
updated here - https://github.com/projectdiscovery/dnsx/pull/241
