### ISSUE TITLE
[issue] QueryMultiple Logic

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/dnsx#25]
**Describe the bug**
An error within one of the query types causes a global fail
https://github.com/projectdiscovery/dnsx/blob/cf9498dfb27e0e6cb36b76a26bed506baf872b53/internal/runner/runner.go#L308

**Comment by zt2** [comment]
Please see https://github.com/projectdiscovery/retryabledns/issues/15

**Comment by Mzack9999** [comment]
Closing as the issue is addressed in dnsx at #33 . Let us know if you still face problems, thanks!
