### ISSUE TITLE
Show found subdomains in output for -axfr

### ISSUE THREAD

**Issue by gprime31** [projectdiscovery/dnsx#250]
![2022-10-15_09-03](https://user-images.githubusercontent.com/44535257/195987862-da99ee90-7d82-4531-8931-c21eb18e4438.png)

Should look like:

![2022-10-15_09-04](https://user-images.githubusercontent.com/44535257/195987895-3c0e9d81-1e44-4465-a9c8-b323db1441d0.png)

If it shows with -v flag that's fine too.

**Comment by brenocss** [comment]
` echo zonetransfer.me | dnsx -axfr -json | jq '.axfr.chain[].all[]' -r | awk '{print $1}'| anew ` maybe this can help you

**Comment by Mzack9999** [comment]
@gprime31, you should be able to extract this info with `-json` and jq, as showed by @brenocss
