### ISSUE TITLE
DNSX stucks if trying to use list

### ISSUE THREAD

**Issue by mastercho** [projectdiscovery/dnsx#345]
### Current Behavior:
Using `-l` param stucks example

```
$ ./dnsx.exe -l tamambet142.txt -cname -resp

      _             __  __
   __| | _ __   ___ \ \/ /
  / _' || '_ \ / __| \  /
 | (_| || | | |\__ \ /  \
  \__,_||_| |_||___//_/\_\

                projectdiscovery.io

[INF] Current dnsx version 1.1.3 (latest)
```

if i use `cat `instead `-l` its works

```
$ cat tamambet142.txt  | ./dnsx.exe -cname -resp

      _             __  __
   __| | _ __   ___ \ \/ /
  / _' || '_ \ / __| \  /
 | (_| || | | |\__ \ /  \
  \__,_||_| |_||___//_/\_\

                projectdiscovery.io

[INF] Current dnsx version 1.1.3 (latest)
www.tamambet142.com [tamambet142.com]
m.tamambet142.com [tamambet142.com]


```

### Expected Behavior:
To read list like cat when -l is specified
### Steps To Reproduce:
`dnsx.exe -l list.txt -cname -resp
`

![Screenshot](https://ruri.please-fuck.me/60KDgIlDx.png)

**Comment by RamanaReddy0M** [comment]
@mastercho can you please try the latest version(1.1.4)?

I tried the latest version and it worked.
![Screenshot 2023-06-01 at 4 12 05 PM](https://github.com/projectdiscovery/dnsx/assets/90540245/5bb4e287-b34d-41cd-ab55-6786e924a3ee)

let me know if the problem still persists, thank you.

**Comment by mastercho** [comment]
Unfortunately still having same issue with `-l`

**Comment by hastalamuerte** [comment]
dnsx.exe -l .\httpx.txt -a -o ip.txt
dnsx.exe -l .\httpx.txt -a  -aaaa  -cname -o ip.txt
 dnsx.exe domain.com 
dnsx.exe -l .\httpx.txt --o ip.txt
 not any variants are working) with list of urls . with or without http or https......
