### ISSUE TITLE
Export `runner` to use as lib

### ISSUE THREAD

**Issue by gnuletik** [projectdiscovery/dnsx#351]
### Please describe your feature request:
The `runner` package is currently located inside `internal` directory (https://github.com/projectdiscovery/dnsx/tree/main/internal/runner) which makes it unable to load it as a library.

Would it be possible to move `internal/runner` to `libs/runner` (or `pkg/runner`) so it can be imported inside other projects?

Is there a specific reason to put it inside `internal`?
Other projectdiscovery projects like seems to export the runner package.
e.g. https://github.com/projectdiscovery/subfinder/tree/master/v2/pkg/runner

### Describe the use case of this feature:

We'd like to use the bruteforce feature inside other projects.

If you're okay with this, I can make a PR for the migration.
Thanks!

**Comment by okadwin** [comment]
I encountered the same problem, the libs/dnsx package provides too few feature and option

**Comment by dogancanbakir** [comment]
@gnuletik,
@okadwin,
Please provide your thoughts and suggestions on the features you want to see in libs/dnsx. Thanks!

**Comment by dogancanbakir** [comment]
We have considered your request to export the runner, but have decided that it goes against our current conventions. However, we welcome your suggestions and would be happy to consider incorporating new features into our library. To suggest features, please create a new issue and we will review it as soon as possible. Thank you for your understanding.
