### ISSUE TITLE
Inconsistent results between multiple runs using any flag

### ISSUE THREAD

**Issue by secinto** [projectdiscovery/dnsx#481]
### Current Behavior:

The amount of resolved DNS entries varies between different runs of dnsx. 

### Expected Behavior:

Same amount of results between all runs.
### Steps To Reproduce:

subfinder -d akern.at | dnsx -any -resp -json 

Only a subset of the hosts are resolved and returned (but always the same amount). 
20 versus 26 in my case. If use the flags I am interested in always results for all are returned.

### Anything else:

![dnsx_issue](https://github.com/projectdiscovery/dnsx/assets/53216721/0de8a5e2-ac3a-48b2-a59a-3d230dcebeef)

**Comment by olearycrew** [comment]
@secinto it looks like you had different types selected in those runs. Also I'm wondering if the jq filter is impacting it too.

**Comment by olearycrew** [comment]
Would be great to see a raw `-silent` output and the same exact options run.

If you want to share your target domains with us privately to help us diagnose more directly, join our Discord server and reach out there: https://nux.gg/discord

**Comment by secinto** [comment]
The question is should there a difference between using "any" flag and "all" explicit types (such as a, aaaa, cname, ....). From the DNS specification the ANY Type should request all info from the DNS server, but since it has been used for DoS amplification it could be that not all servers are responding correctly to it. Thus, the question is first, is it implemented with an explicit "ANY" request or (and from the implementation it seems that way) does it just output all information. If the second is true thant there is somewhere a bug since not the same amount of servers are resolved for the same domains.

**Comment by ehsandeep** [comment]
@secinto `-any` is for explicit `ANY` dns query and should not be used as an alternative to other record type, as you mentioned, `-any` is not going to work for most of the servers and should be only used if you are only and specifically looking to make `ANY` query to specific servers.

**Comment by secinto** [comment]
@ehsandeep Thx for the clarification. Than I would say it behaves as standardized ;)
