### ISSUE TITLE
DNSX panics on CIDR mapping

### ISSUE THREAD

**Issue by ghost** [projectdiscovery/dnsx#500]
### dnsx version:
1.1.6

### Current Behavior:
When scanning a list of domains for subdomains, using a wordlist I get the following panic error during ASN mapping.

Looks like the asnmap response returned when scanning may return invalid data which is not handled correctly. It looks to return a dataset with several missing fields.

This is on WIndows 11 64b, with go version go1.21.4 windows/amd64

```
panic: runtime error: index out of range [15] with length 0

goroutine 576 [running]:
github.com/projectdiscovery/mapcidr.ipNetToRange({{0x0, 0x0, 0x0}, {0xc004af0210, 0x10, 0x10}})
        %WIN_HOME%/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.15/ip.go:289 +0x4a5
github.com/projectdiscovery/mapcidr.partitionCIDR({{0xc004af01a0, 0x10, 0x10}, {0xc004af01b0, 0x10, 0x10}}, {{0x0, 0x0, 0x0}, {0xc004af0210, ...}})
        %WIN_HOME%/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.15/ip.go:622 +0x197
github.com/projectdiscovery/mapcidr.rangeToCIDRs({0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
        %WIN_HOME%/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.15/ip.go:599 +0x67d
github.com/projectdiscovery/mapcidr.GetCIDRFromIPRange({0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
        %WIN_HOME%/go/pkg/mod/github.com/projectdiscovery/mapcidr@v1.1.15/ip.go:1058 +0x130
github.com/projectdiscovery/asnmap/libs.GetCIDR({0xc0020bc870, 0x1, 0x1?})
        %WIN_HOME%/go/pkg/mod/github.com/projectdiscovery/asnmap@v1.0.6/libs/cidr.go:12 +0x1c5
github.com/projectdiscovery/dnsx/internal/runner.(*Runner).worker(0xc000132780)
        C:/git/dnsx/internal/runner/runner.go:701 +0x932
created by github.com/projectdiscovery/dnsx/internal/runner.(*Runner).startWorkers in goroutine 1
        C:/git/dnsx/internal/runner/runner.go:614 +0xb6
```

### Expected Behavior:
Previous versions has completed the same search correctly.

### Steps To Reproduce:
1. Download the latest repo
2. go mod download
3. go build .\cmd\dnsx
4. The command run for enumeration is `.\dnsx\dnsx.exe -a -cname -mx -txt -asn -w .\datasets\wordlist-fqdn-sorted.txt -retry 1 -r 1.0.0.1,8.8.4.4,149.112.112.112 -json -t 1500 -o .\dnsx.json -d .\domains.txt`

After adding an error print message on line 700 `dnsx/internal/runner/runner.go` I got the following message, which shows that the start and end field of the asnmap.Response are missing.
`gologger.Error().Msgf("%s - %d results: %s", domain, len(results), results)`  

`[ERR] interactintegrasjoner.DOMAIN- 1 results: [%!s(*asnmap.Response=&{  HOST_IPv4 ASN NUMBER COUNTRY_CODE ASNNAME Peering: ASN_EMAIL})]`

Running DNSX looking just for this FQDN, ``, it runs okay and returns a better ASNmap.  
`.\dnsx.exe -a -cname -mx -txt -asn -w interactintegrasjoner -retry 1 -r 1.0.0.1,8.8.4.4,149.112.112.112 -json -t 1500 -d DOMAIN`  

`[ERR] interactintegrasjoner.DOMAIN - 1 results: [%!s(*asnmap.Response=&{IP_NET_START IP_NET_END  ASN NUMBER COUNTRY_CODE ASNNAME Peering: ASN_EMAIL})]`

**Comment by kcertmagnuso** [comment]
After more testing, it appears this is due to scanning beyond capability probably.  As i ran it with 1500 threads, scaling down to 500 seems to work fine.
So maybe adding a better error handling for asnmap lookup would suffice.

**Comment by dogancanbakir** [comment]
Depends on https://github.com/projectdiscovery/mapcidr/pull/279
