### ISSUE TITLE
Not show NS record for some domains

### ISSUE THREAD

**Issue by j4i4i** [projectdiscovery/dnsx#513]
Not show NS record for some domains, example: google.com bing.com

OS: Linux 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$: **echo google.com | ./dnsx -json -ns | jq**

[INF] Current dnsx version 1.1.6 (latest)
{
  "host": "google.com",
  "resolver": [
    "1.0.0.1:53",
    "8.8.8.8:53"
  ],
  "status_code": "NOERROR",
  "timestamp": "2023-12-01T05:29:39.513343818+03:30"
}

ok for yahoo.com:
$: **echo yahoo.com | ./dnsx -json -ns | jq**

[INF] Current dnsx version 1.1.6 (latest)
{
  "host": "yahoo.com",
  "ttl": 168344,
  "resolver": [
    "1.0.0.1:53"
  ],
  "ns": [
    "ns4.yahoo.com",
    "ns5.yahoo.com",
    "ns2.yahoo.com",
    "ns3.yahoo.com",
    "ns1.yahoo.com"
  ],
  "all": [
    "yahoo.com.\t168344\tIN\tNS\tns4.yahoo.com.",
    "yahoo.com.\t168344\tIN\tNS\tns5.yahoo.com.",
    "yahoo.com.\t168344\tIN\tNS\tns2.yahoo.com.",
    "yahoo.com.\t168344\tIN\tNS\tns3.yahoo.com.",
    "yahoo.com.\t168344\tIN\tNS\tns1.yahoo.com.",
    "\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags:; udp: 1232"
  ],
  "status_code": "NOERROR",
  "timestamp": "2023-12-01T05:33:44.657175352+03:30"
}

**Comment by ehsandeep** [comment]
```
$ echo google.com | dnsx -j -ns | jq .

      _             __  __
   __| | _ __   ___ \ \/ /
  / _' || '_ \ / __| \  / 
 | (_| || | | |\__ \ /  \ 
  \__,_||_| |_||___//_/\_\

		projectdiscovery.io

[INF] Current dnsx version 1.1.6 (latest)
{
  "host": "google.com",
  "ttl": 329740,
  "resolver": [
    "1.0.0.1:53"
  ],
  "ns": [
    "ns4.google.com",
    "ns2.google.com",
    "ns1.google.com",
    "ns3.google.com"
  ],
  "all": [
    "google.com.\t329740\tIN\tNS\tns4.google.com.",
    "google.com.\t329740\tIN\tNS\tns2.google.com.",
    "google.com.\t329740\tIN\tNS\tns1.google.com.",
    "google.com.\t329740\tIN\tNS\tns3.google.com.",
    "\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags:; udp: 1232"
  ],
  "status_code": "NOERROR",
  "timestamp": "2024-03-02T01:24:00.215328+05:30"
}

$ echo bing.com | dnsx -j -ns | jq .

      _             __  __
   __| | _ __   ___ \ \/ /
  / _' || '_ \ / __| \  / 
 | (_| || | | |\__ \ /  \ 
  \__,_||_| |_||___//_/\_\

		projectdiscovery.io

[INF] Current dnsx version 1.1.6 (latest)
{
  "host": "bing.com",
  "ttl": 245,
  "resolver": [
    "1.0.0.1:53"
  ],
  "ns": [
    "ns1-204.azure-dns.com",
    "ns2-204.azure-dns.net",
    "ns3-204.azure-dns.org",
    "ns4-204.azure-dns.info",
    "dns1.p09.nsone.net",
    "dns2.p09.nsone.net",
    "dns3.p09.nsone.net",
    "dns4.p09.nsone.net"
  ],
  "all": [
    "bing.com.\t245\tIN\tNS\tns1-204.azure-dns.com.",
    "bing.com.\t245\tIN\tNS\tns2-204.azure-dns.net.",
    "bing.com.\t245\tIN\tNS\tns3-204.azure-dns.org.",
    "bing.com.\t245\tIN\tNS\tns4-204.azure-dns.info.",
    "bing.com.\t245\tIN\tNS\tdns1.p09.nsone.net.",
    "bing.com.\t245\tIN\tNS\tdns2.p09.nsone.net.",
    "bing.com.\t245\tIN\tNS\tdns3.p09.nsone.net.",
    "bing.com.\t245\tIN\tNS\tdns4.p09.nsone.net.",
    "\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags:; udp: 1232"
  ],
  "status_code": "NOERROR",
  "timestamp": "2024-03-02T01:24:11.116214+05:30"
}
```

Not able to reproduce it.
