### ISSUE TITLE
DNSx unstable and can't write in json output 

### ISSUE THREAD

**Issue by themeswordpress** [projectdiscovery/dnsx#519]
the output not write in the json file 

dnsx.exe -silent -l 2579_full.txt-t 10 -a -re -asn -json test.json

and the another issue is when scan with -t 100 the results is totally different i.e when scan with 10 the dnsx scan only the first 500 lines but when make it 10 the dnsx scan first 1800 files (my total lines are 2579 )   and

**Comment by dogancanbakir** [comment]
@themeswordpress, Can you retry with
```
dnsx.exe -silent -l 2579_full.txt -t 10 -a -re -asn -json -output test.json
```
`-j, -json           write output in JSONL(ines) format` is a boolean flag. For specifying a file, you can use `-o, -output string  file to write output`.

Let us know how it goes!

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if the issue persists.
