### ISSUE TITLE
I'd like it to support HTTPS records for requesting ECH configuration information   

### ISSUE THREAD

**Issue by LiFulian** [projectdiscovery/dnsx#587]

**Comment by olearycrew** [comment]
@LiFulian I'm not sure I can envision how this works - and would it be better as part of tlsx maybe? https://github.com/projectdiscovery/tlsx

I'll admint I don't know enough about ECH and how it interacts with DNS to know.

**Comment by Mzack9999** [comment]
@LiFulian I'm closing due to lack of details - Feel free to provide more details and we will be happy to look into it. Thanks!
