### ISSUE TITLE
Installation Issue with dnsx v1.2.0 Using go install

### ISSUE THREAD

**Issue by hahwul** [projectdiscovery/dnsx#588]
Hi,
I've encountered an issue while attempting to install dnsx version 1.2.0 using Go. 

When running the command to install dnsx using Go, I encounter an error message that suggests there's a problem with the go.mod file of the dnsx module, specifically regarding the use of replace directives.

### dnsx version:
v1.2.0

### Current Behavior:
```
$ go install github.com/projectdiscovery/dnsx/cmd/dnsx@latest
go: github.com/projectdiscovery/dnsx/cmd/dnsx@latest (in github.com/projectdiscovery/dnsx@v1.2.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

### Expected Behavior:
The expected behavior is for dnsx to be installed successfully without encountering errors related to the module's go.mod file.

### Steps To Reproduce:
1. Install dnsx with go install
```
go install github.com/projectdiscovery/dnsx/cmd/dnsx@latest
```

**Comment by ehsandeep** [comment]
@hahwul fixed in https://github.com/projectdiscovery/dnsx/releases/tag/v1.2.1
