### ISSUE TITLE
Problem with simultaneus scans [Could not read statistics]

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/dnsx#709]
### dnsx version:
1.2.1

### Current Behavior:
While running 2 or more dnsx scans, the following error is shown: 

`[ERR] Could not read statistics: [:RUNTIME] Error getting /metrics response: Get "http://127.0.0.1:43591/metrics": dial tcp 127.0.0.1:43591: connect: connection refused `

### Expected Behavior:
Handle multiple scans. 

### Steps To Reproduce:

1. Run scan 1 with enough domains to keep it running for a couple of minutes
2. Run scan 2 with same conditions as 1.

See the error in the second scan.

**Comment by dogancanbakir** [comment]
I wasn't able to repro the issue. Could you please share the exact command you used?

**Comment by pdelteil** [comment]
> I wasn't able to repro the issue. Could you please share the exact command you used?

Hello,

I checked and this only happens with -v flag, which is expected behavior I believe.

Just in case, command (2 times simultaneously) :  `cat domains.txt| dnsx -v -stats -rc servfail `
