### ISSUE TITLE
`-ptr` flag combined with one of `-mx`, `-ns`, `-txt`, `caa`, `-srv`, `-axfr`, `-soa`  doesn't return anything

### ISSUE THREAD

**Issue by ocervell** [projectdiscovery/dnsx#762]
If I run:

```
echo 8.8.8.8 | dnsx -resp -a -aaaa -cname -mx -ns -txt -srv -ptr -soa -axfr -caa -threads 50
```

I'm getting 0 results.

If I run with just `-ptr` flag, it returns the PTR record:
```
echo 8.8.8.8 | dnsx -resp -ptr -threads 50
8.8.8.8 [PTR] [dns.google] 
```

Note that `-recon` works.

I try to 'bisect' to find which flags causes the issue, and it seems the problem is when adding one of the flags `-mx`, `-ns`, `-txt`, `-caa`, `-srv`, `-axfr`, `-soa` I'm not getting PTR results anymore.

**Comment by dogancanbakir** [comment]
There is an implicit decision to reduce the exec time https://github.com/projectdiscovery/dnsx/blob/dev/libs/dnsx/dnsx.go#L136. That's also the reason behind why `-recon` works. Feel free to reopen if you have any other questions.
