### ISSUE TITLE
Extra color symbols when writing files

### ISSUE THREAD

**Issue by Mengter8** [projectdiscovery/dnsx#763]
### Steps To Reproduce:
echo www.google.com | ./dnsx -a -resp -o dnsx.csv

### Anything else:
This problem does not exist when I add the -no-color parameter

![image](https://github.com/user-attachments/assets/8c272b43-fee0-4d2a-a603-676dd17c12be)

**Comment by ehsandeep** [comment]
@Mengter8 use `-nc` option

```
   -nc, -no-color  disable color in output
```
